version: '3'

networks:
  counter:
    external: true

services:
  counter-db:
    image: postgres:10.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: counter
      POSTGRES_USER: counter
      POSTGRES_PASSWORD: counter-pass
    networks:
      - counter